### ISSUE TITLE
How to add "/" into the path?

### ISSUE THREAD

**Issue by adamwuyu** [dvajs/dva#872]
When I set route path '/data/extra', there will be an error:

> index.js:1 Uncaught SyntaxError: Unexpected token <

Here is the code piece:
const routes = [
    {
      path: '/data/extra',
      name: 'Extra',
      getComponent(nextState, cb) {
        require.ensure([], (require) => {
          registerModel(app, require('./models/users'));
          cb(null, require('./routes/data/Extra'));
        });
      },
    },
  ];

Any idea?

**Comment by oluckyman** [comment]
I have the same problem. Found that it’s because of relative `index.js` path in the `index.html`:
```
<script src="index.js"></script>
```
so in nested URLs like `/xxx/yyy` it tries to load `index.js` from `/xxx/index.js` URL.
I’ve made it work in my local dev environment by setting absolute path:
```
<script src="/index.js"></script>
```
But I’m not sure if it’s proper way to do this? will it work on prod environment?
